apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  restaurantdb_url: RESTAURANT_DB_URL
  foodcataloguedb_url: FOOD_CATALOGUE_DB_URL
  userdb_url: USER_DB_URL
  orderdb_url: ORDER_DB_URL
  eureka_service_address: EUREKA_URL

  
  # restaurantdb: restaurantdb
  # mysql-server: mysql-service    # The name of mysql service
  # mysql-user-username: root
  # citizen_database_url: jdbc:mysql://mysql-service:3306/citizendb
  # foodcataloguedb_url: jdbc:mysql://mysql-service:3306/foodcataloguedb
  # userdb_url: jdbc:mysql://mysql-service:3306/userdb
  # foodcataloguedb: foodcataloguedb
  # userdb: userdb
  